---
# Hide toc (can't see headers in grid)
toc: false

# Specify full page layout
page-layout: article
---

### {{< fa comment >}} &nbsp;About Me...
I am a Specialty Registrar in Cardiology (ST6) with a subspeciality interest in coronary intervention. When I'm not in the Cath Lab or on the Coronary Care Unit, you'll probably find me behind a computer, analysing data or trying to persuade a machine learning model to work.

::: {.grid}

::: {.g-col-8}

### {{< fa graduation-cap >}} &nbsp;University Education

- **PhD**<br>2025 (expected) | University of Leeds, UK.<br> Supervisors: Marlous Hall, Ben Brown & Mark Kearney.
- **BSc(Hons) in Computer Science (Data Science)**<br>2012 | First class | University of London, UK.
- **MPH in Quantitative Methods**<br>2017 | GPA 3.9 | Harvard University, USA.
- **MBChB(Hons) in Medicine and Surgery**<br>2014 | With Honours | University of Leeds, UK.
- **BSc(Hons) in Clinical Sciences in Relation to Medicine**<br>2012 | First class | University of Leeds, UK.

### {{< fa stethoscope >}} &nbsp; Medical Education
- **European Exam in Core Cardiology (EECC)**<br>2022 | European Society of Cardiology.
- **Diploma in Geriatric Medicine (DGM)**<br>2019 | Royal College of Physicians, London, UK.
- **Membership of the Royal College of Physicians (MRCP)** <br> 2018 | Royal College of Physicians London, UK.

### {{< fa briefcase >}} &nbsp;Employment & Experience

- **Clinical Research Fellow** <br>
University of Leeds, Leeds, UK. <br>
2022 - present.
- **Specialty Trainee in Cardiology (ST3 - ST6)** <br>
NHS England Workforce, Training and Education: North East <br>
2021 - 2022 | James Cook University Hospital, Middlesbrough <br>
2022 - 2022 | Sunderland Royal Hospital, Sunderland <br>
2020 - 2021 | University Hospital of North Tees, Stockton-on-Tees <br>
2020 - 2021 | The Cumberland Infirmary, Carlisle
- **Core Medical Training (ST1 - ST2)** <br>
NHS England Workforce, Training and Education: West Midlands <br>
2017 - 2019 | University Hospital, Coventry and St Cross Hospital, Rugby
- **Academic Foundation Training (aFY1 - aFY2) in Cardiology** <br>
NHS England Workforce, Training and Education: North East <br>
2015 - 2016 | The Freeman Hospital, Newcastle upon Tyne <br>
2014 - 2015 | The Royal Victoria Infirmary, Newcastle upon Tyne

### {{< fa building-columns >}} &nbsp;Fellowships and Scholarships
- **Wellcome Trust Clinical PhD Fellowship** (£303,471) <br>
2022 - present | 4Ward North PhD Programme for Health Professionals
- **Knox Fellowship** (£66,703) <br> 
2016 - 2017 | Harvard University, USA.
- **The LEAD Scholarship** (£5,000) <br>
2011 - 2012 | University of Leeds Alumni Fund.
- **The Wolfson Intercalated Degree Scholarship** (£5,000) <br>
2011 - 2012 | The Royal College of Physicians.
- **Heart Research UK EXSEL/LURE Scholarship** (£8,000) <br>
2009 - 2014 | Heart Research UK,

### {{< fa award >}} &nbsp;Prizes
- **Royal Society of Medicine Medical Authors’ Prize** <br>
2015 - first runner-up | The Royal Society of Medicine.
- **Society for Academic and Research Surgery Medical Student Prize** <br>
2014 - finalist | The Society for Academic and Research Surgery.
- **The Chris Church Medal** <br>
2013 - winner | University of Leeds.
- **The Leeds Medico-Chirurgical Society Intercalated Prize** <br>
2012 - winner | The Leeds Medico-Chirurgical Society.
- **The Healthwatch UK Student Prize** <br>
2012 - winner | HealthWatch UK.
- **The Willis Prize** <br>
2012 - winner | University of Leeds.
- **The Infirmary Prize** <br>
2010 - winner | University of Leeds.
- **The Silversides Prize** <br>
2010 - winner | University of Leeds.
- **The Charles Turner Thackrah Prize**  <br>
2010 - winner | University of Leeds.
- **The Malcolm Levine Award**  <br>
2010 - winner | University of Leeds.

### {{< fa book >}} &nbsp;Publications
#### Journal Articles
<ol reversed>
	<li>Hayward CJ, **Batty JA**, Westhead DR, Johnson O, Gale CP, Wu J, Hall M. Disease trajectories following myocardial infarction: insights from process mining of 145 million hospitalisation episodes. eBioMedicine, 2023 Oct; 96: 104792. doi: 10.1016/j.ebiom.2023.104792. Epub 2023 Sep 21. PMID: pending.</li>
	<li>**Batty JA**, Hall M. Trends in ACEi and ARB expenditure: Compelling case for competition in generic drug markets. Int J Cardiol. 2023 Jan 1;370:419-420. doi: 10.1016/j.ijcard.2022.11.027. Epub 2022 Nov 19. PMID: 36414045.</li>
	<li>Telyuk P, Hancock H, Maier R, **Batty JA**, Goodwin A, Owens WA, Ogundimu E, Akowuah E. Long-term outcomes of mini-sternotomy versus conventional sternotomy for aortic valve replacement: a randomized controlled trial. Eur J Cardiothorac Surg. 2022 Dec 2;63(1):ezac540. doi: 10.1093/ejcts/ezac540. PMID: 36394261.</li>
	<li>Gu SZ, Qiu W, **Batty JA**, Sinclair H, Veerasamy M, Brugaletta S, Neely D, Ford G, Calvert PA, Mintz GS, Kunadian V. Coronary artery lesion phenotype in frail older patients with non-ST-elevation acute coronary syndrome undergoing invasive care. EuroIntervention. 2019 Jun 12;15(3):e261-e268. doi: 10.4244/EIJ-D-18-00848. PubMed PMID: 30777840.</li>
	<li>Gu SZ, Beska B, Chan D, Neely D, **Batty JA**, Adams-Hall J, Mossop H, Qiu W, Kunadian V. Cognitive Decline in Older Patients With Non- ST Elevation Acute Coronary Syndrome. J Am Heart Assoc. 2019 Feb 19;8(4):e011218. doi: 10.1161/JAHA.118.011218. PubMed PMID: 30773118; PubMed Central PMCID: PMC6405683.</li>
	<li>**Batty JA**, Qiu W, Gu S, Sinclair H, Veerasamy M, Beska B, Neely D, Ford G, Kunadian V. One-year clinical outcomes in older patients with non-ST elevation acute coronary syndrome undergoing coronary angiography: An analysis of the ICON1 study. Int J Cardiol. 2019 Jan 1;274:45-51. doi: 10.1016/j.ijcard.2018.09.086. Epub 2018 Sep 28. PubMed PMID: 30287058.</li>
	<li>Dordea M, Moore U, **Batty JA**, Lennard TWJ, Aspinall SR. Correlation of surgeon-performed parathyroid ultrasound with the Perrier classification and gland weight. Langenbecks Arch Surg. 2018 Nov;403(7):897-903. doi: 10.1007/s00423-018-1714-x. Epub 2018 Oct 20. PubMed PMID: 30343413.</li>
	<li>**Batty JA**, Tang M, Hall M, Ferrari R, Strauss MH, Hall AS. Blood pressure reduction and clinical outcomes with angiotensin-converting enzyme inhibitors and angiotensin II receptor blockers: protocol for a systematic review and meta-regression analysis. Syst Rev. 2018 Aug 25;7(1):131. doi: 10.1186/s13643-018-0779-5. PubMed PMID: 30144828; PubMed Central PMCID: PMC6109343.</li>
	<li>**Batty JA**, Tang M. Prevalence of Pulmonary Embolism among Patients Hospitalized for Syncope [correspondence]. N Engl J Med 2017; 376:494-497.</li>
	<li>Sinclair H, **Batty JA**, Qiu W, Kunadian V. Engaging older patients in cardiovascular research: observational analysis of the ICON-1 study. Open Heart. 2016; 3(2): e000436. doi: 10.1136/openhrt-2016-000436. PMID 27547431.</li>
	<li>Kunadian V, Neely D, Sinclair H, **Batty JA**, Lima JAC, Veerasamy M, Ford GA, Qiu W. A study to improve cardiovascular outcomes in high risk older patients with acute coronary syndrome - ICON1 study design and protocol. BMJ Open. 2016; 23;6(8):e012091. doi: 10.1136/bmjopen-2016-012091. PMID 27554105.</li>
	<li>Lima Jr JAC, **Batty JA**, Sinclair H, Kunadian V. MicroRNAs in Ischemic Heart Disease: From Pathophysiology to Potential Clinical Applications. Cardiol Rev. 2016; [Epub ahead of print]. PMID 27465537.</li>
	<li>Latimer J, **Batty JA**, Neely RD, Kunadian V. PCSK9 inhibitors in the prevention of cardiovascular disease. J Thromb Thrombolysis. 2016 Oct; 42(3): 405-19. doi: 10.1007/s11239-016-1364-1. 27095708</li>
	<li>**Batty JA**, Subba S, Luke P, Gigi LWC, Sinclair H, Kunadian V. intracoronary imaging in the detection of vulnerable plaques. Curr Cardiol Reports. 2016; 18(3):28. doi: 10.1007/s11886-016-0705-1. PMID 26879196.</li>
	<li>**Batty JA**, Lima Jr JAC, Kunadian V. Direct cellular reprogramming for cardiac repair and regeneration. Eur J Heart Fail. 2016; doi: 10.1002/ejhf.446. PMID: 26635186.</li>
	<li>Rodham P, **Batty JA**, McElnay PJ, Immanuel A. Does minimally invasive oesophagectomy provide a benefit in hospital length of stay when compared with open oesophagectomy? Interact Cardiovasc Thorac Surg. 2016; 22(3): 360-7. doi: 10.1093/icvts/ivv339. PMID: 26669851.</li>
	<li>**Batty JA**. RE: Association between day of delivery and obstetric outcomes: observational study [Rapid Response]. BMJ 2015; 351: h5774 (available http://www.bmj.com/content/351/bmj.h5774/rr)</li>
	<li>**Batty JA**, Hall AS, White HL, Wikstrand J, de Boer RA, van Veldhuisen DJ, van der Harst P, Hjalmarsond Å, Kjekshus J & Balmforth AJ, on behalf of the MERIT-HF Study Group. An investigation of cytochrome P450 2D6 genotype and response to metoprolol CR/XL during dose-titration in patients with chronic heart failure: a MERIT-HF sub-study. Clinical Pharmacology and Therapeutics. 2013. doi: 10.1038/clpt.2013.193. PMID: 24193112.</li>
	<li>**Batty JA**. Big Bad Pharma? Student BMJ. 2013; 21: f447. doi: 10.1136/sbmj.f447</li>
</ol>

#### Book Chapters
<ol reversed>
<li>**Batty JA**, Dunford J, Dangas G, Kunadian V. Chapter 39: Oral Antiplatelet Agents in Percutaneous Coronary Intervention, in: Interventional Cardiology: Principles and Practice, 2nd Ed. 2017: Wiley, Hoboken, New Jersey, USA.</li>
<li>**Batty JA**, Dunford J, Mehran R, Kunadian V. Chapter 45: Triple Antiplatelet Therapy and Combinations with Oral Anticoagulants after Percutaneous Coronary Intervention, in: Interventional Cardiology: Principles and Practice, 2nd Ed. 2017: Wiley, Hoboken, New Jersey, USA.</li>
<li>**Batty JA**. Leeds Medical School. In: Sanders S, Metcalfe D, Dev H. So You Want To Be A Doctor? 2nd ed. 2013. Oxford: Oxford University Press. ISBN: 978-0-19-968686-5.</li>
</ol>

### {{< fa person-chalkboard >}} &nbsp;Conference Abstracts
#### Oral Presentations
<ol reversed>
	<li>**Batty JA**, Haq IU. The Diagnosis of Stable Angina: is there still a role for the Rapid Access Chest Pain Clinic? Association of North East Physicians (North Tees University Hospital). March 2015.</li>
	<li>Dordea M, Moore N, **Batty JA**, Lennard TWJ, Aspinall SR. Correlation of surgeon-performed parathyroid ultrasound with the Perrier classification and gland weight. BJS Prize session, 35th Annual BAETS Scientific meeting (Reading/Henley-on-Thames, UK; October 2015).</li>
	<li>**Batty JA**, Bailey MA, Patel J, Kay SP, Scott DJA. Outcomes in Paget-Schroetter syndrome: surgical thoracic outlet decompression reduces the risk of upper extremity deep venous re-thrombosis. Yorkshire Vascular Society Meeting 2014 (March 2014).</li>
	<li>**Batty JA**. The ‘third option’ for carotid endarterectomy: patient co-operative general anaesthesia. A case report. Yorkshire Society of Anaesthetists 2014 Annual Meeting (January 2014).</li>
	<li>**Batty JA**, Bailey MA, Adeogun A, Fairbrass K, Bridge KI, Johnson AB, Walker PG, Ariëns RA, Scott DJ. The association of visceral adiposity with abdominal aortic aneurysm presence, size and ex vivo fibrin clot structure. Society for Academic and Research Surgery (SARS) 2014 Annual Meeting (January 2014).  Abstract published in British Journal of Surgery (May 2014). PMID: 24737282.</li>
	<li>**Batty JA**, Hall AS, Balmforth AJ. Statin Therapy in Women - From Controversy to Consensus? A Systematic Review and Meta-Analysis. 10th International Congress on Coronary Artery Disease: Proceedings of the 2013 Congress, Abstract published in Cardiology (October 2013). PMID: 24157618.</li>
	<li>**Batty JA**, Hall AS, Braund PS, Nelson CP, Samani NJ, Balmforth AJ. Long-Term Prognosis of Premature, Familial Coronary Artery Disease: 10-Year Analysis of The British Heart Foundation Family Heart Study (BHF-FHS). 10th International Congress on Coronary Artery Disease: Proceedings of the 2013 Congress. Abstract published in Cardiology (October 2013). PMID: 24157618.</li>
	<li>**Batty JA**, Hall AS, Balmforth AJ. A multivariable coronary artery disease genetic risk model offers incremental predictive power in early-onset, high-risk families. Leeds Med Chir Society (October 2012).</li>
</ol>

#### Poster Presentations
<ol reversed>
    <li>Hayward C, **Batty JA**, Westhead DR, Johnson O, Gale CP, Wu J, Hall M. Disease trajectories following myocardial infarction: insights from process mining of 145 million hospitalisation episodes. European Society of Cardiology Congress 2023, Amsterdam, The Netherlands.</li>
	<li>Hall M, Smith L, Wu J, Hayward C, **Batty JA**, Lambert PC, Hemingway H, Gale CP. Health outcomes after myocardial infarction: a population study of 56 million people in England. European Society of Cardiology Congress 2023, Amsterdam, The Netherlands.</li>
	<li>Hall M, Smith L, Wu J, Hayward C, **Batty JA**, Lambert PC, Hemingway H, Gale CP. Health outcomes after myocardial infarction: a population study of 56 million people in England. European Society of Cardiology Congress 2023, Amsterdam, The Netherlands.</li>
	<li>Bennet M and **Batty JA**. The impact of frailty on the management and outcome of ST-elevation myocardial infarction in older patients. European Society of Cardiology Congress 2021 (e-conference due to COVID-19 pandemic).</li>
	<li>Abdelsalam B, **Batty JA**, Hann K, Hunt T, Hardy L, Coverdale K, Renwick E, Baker A, Dewhurst MJ. Rapid Pharmacological Optimisation With an Angiotensin Receptor-Neprilysin Inhibitor (Sacubitril/Valsartan) In De Novo Severe Left Ventricular Systolic Dysfunction: Effects on Left Ventricular Systolic Function And Time to Optimisation Of Therapy. Heart Failure 2021 (e-conference due to COVID-19 pandemic).</li>
	<li>**Batty JA**, Gupta A, Buchanan GL, Shome J. Left main bifurcation PCI using a dual radial ‘ping-pong’ strategy in STEMI with cardiogenic shock and recurrent VT. EuroPCR (Paris, France). May 2020. Accepted for presentation but cancelled due to COVID-19 pandemic.</li>
	<li>Gupta A, **Batty JA**, Barclay J, Shome J. Anterior STEMI complicated by left main stem saddle thrombus. EuroPCR (Paris, France). May 2020. Accepted for presentation but cancelled due to COVID-19 pandemic.</li>
	<li>Gu SZ, **Batty JA**, Jordan R, Veerasamy M, Sinclair H, Bagnall A, Purcell I, Spyridopoulos I, Egred M, Zaman A, Das R, Edwards R, Ahmed J, Kunadian V. The association of frailty and coronary artery disease burden in older patients with non-ST-elevation acute coronary syndrome. BCIS 2017. Abstract to be published in Heart (in print).</li>
	<li>Gu SZ, **Batty JA**, Jordan R, Veerasamy M, Sinclair H, Bagnall A, Purcell I, Spyridopoulos I, Egred M, Zaman A, Das R, Edwards R, Ahmed J, Kunadian V. The association of cognitive impairment and coronary artery disease burden in older patients with non-ST elevation acute coronary syndrome. BCIS 2017. Abstract to be published in Heart (in print).</li>
	<li>Gu SZ, Sinclair H, Latimer J, **Batty JA**, Bagnall A, Purcell I, Das R, Spyridopoulos I, Edwards R, Zaman A, Egred E, Ahmed J, Mintz GA, Kunadian V. The association of frailty and coronary artery plaque composition in high-risk older patients with non-ST- elevation acute coronary syndrome. BCIS 2017. Abstract to be published in Heart (in print).</li>
	<li>Nelson KE, Welsh S, **Batty JA**, Lord SW. Timing of Cardiac Rhythm Management Device Complications: Is Day-Case Implantation Safe? British Cardiovascular Society 2016 (Manchester, UK; June 2016). Abstract published in Heart (June 2016).  doi:10.1136/heartjnl-2016-309890.53</li>
	<li>**Batty JA**, Haq IU. The Diagnosis of Stable Angina: is there still a role for the Rapid Access Chest Pain Clinic? British Cardiovascular Society 2016 (Manchester, UK; June 2016). Abstract published in Heart (June 2016). doi:10.1136/heartjnl-2016-309890.82</li>
	<li>Allison C, Darragh L, **Batty JA**, Duignan A, Moore U, Cain H. Improvements in day-case surgery rates for breast cancer. Association of Breast Surgeons 2016 (Manchester, UK; May 2016). Article published in Eur J Surg Oncol (may 2016). doi:10.1016/j.ejso.2016.02.210</li>
	<li>**Batty JA**, Stone EJ, Okonkwo A, Kunadian K. The full publication rate of abstracts presented at the British Cardiovascular Society annual conference remains high, comparing favourably with other cardiology annual scientific sessions worldwide. British Cardiovascular Society 2015 (Manchester, UK; June 2015). Abstract published in Heart (June 2015). doi:10.1136/heartjnl-2015-308066.117</li>
	<li>**Batty JA**, Sharifpour M, Sinclair M, Veerasamy M, Neely D, Martin-Ruiz C, Saretzki G, Kunadian V. Association of telomere length and telomerase activity with clinical parameters in older patients undergoing invasive management of non-ST elevation acute coronary syndrome.  British Cardiovascular Society 2015 (Manchester, UK; June 2015). Abstract published in Heart (June 2015). doi:10.1136/heartjnl-2015-308066.4</li>
	<li>**Batty JA**, Sharifpour M, Veerasamy M, Sinclair H, Neely D, Martin-Ruiz C, Saretzki G, Kunadian V. telomere length is an independent predictor of disease severity in older patients presenting with non-st elevation acute coronary syndrome. American College of Cardiology Scientific Sessions 2015 (San Diego, USA; March 2015). Abstract published in J Am Coll Cardiology (March 2015).</li>
	<li>**Batty JA**, Sharifpour M, Veerasamy M, Sinclair H, Neely D, Saretzki D, Kunadian V. Telomerase Activity in Older Patients Presenting with Non-ST Elevation Acute Coronary Syndrome. American College of Cardiology Scientific Sessions 2015 (San Diego, USA; March 2015). Abstract published in J Am Coll Cardiology (March 2015).</li>
	<li>**Batty JA**, Veerasamy M, Sinclair H, Kunadian V. Platelet Reactivity in Older Patients Undergoing Invasive Management of Non-ST Elevation Acute Coronary Syndrome. American College of Cardiology Scientific Sessions 2015 (San Diego, USA; March 2015). Abstract published in J Am Coll Cardiology (March 2015).</li>
	<li>**Batty JA**, Bailey MA, Chapman S, Fairbrass K, Johnson AB, Bridge KI, Griffin KJ, Walker PG, Scott DJA. Abdominal aortic aneurysm is associated with visceral but not subcutaneous adiposity. The Vascular Society of Great Britain and Ireland Annual Scientific Meeting 2014 (Glasgow, UK; November 2014). Abstract published in British Journal of Surgery (Feb 2015). PMID: 25727501.</li>
	<li>**Batty JA**, Bailey MA, Patel J, Kay SP, Scott DJA. Outcomes in Paget-Schroetter syndrome: surgical thoracic outlet decompression reduces the risk of upper extremity deep venous re-thrombosis. Congress of the Association of Surgeons of Great Britain and Ireland 2014 (Harrogate, UK; April 2014). Abstract published in British Journal of Surgery (Jan 2015). PMID: 25522060.</li>
	<li>**Batty JA**, Patel JV, Scott DJA. Catheter-directed thrombolysis in upper extremity deep vein thrombosis: an audit of interventional radiology outcomes. British Radiology Institute: The Future of Radiology (London, UK; November 2013).</li>
	<li>**Batty JA**, Hall AS, White HL, Wikstrand J, de Boer RA, van Veldhuisen DJ, van der Harst P, Hjalmarson Å, Kjekshus J & Balmforth AJ, on behalf of the MERIT-HF Study Group. An Investigation into the Effect of Cytochrome P450 (CYP)2D6 Genotype on Pharmacokinetics, Pharmacodynamics and Outcomes during Metoprolol CR/XL Therapy in a Heart Failure Cohort: A MERIT-HF Sub-Study. American College of Cardiology Scientific Sessions 2013 (San Francisco, USA; March 2013). Abstract published in J Am Coll Cardiology (March 2013). PMID: 24236310.</li>
</ol>

### {{< fa school >}} &nbsp;Teaching
#### Current
**ENQUIRE2** | 2022 - present <br>
Year 2, MBChB. Role: lecturer and small group tutor.

#### Previous
Journal Club Lead<br>
Bedside teaching (medical students to MRCP PACES level)

### {{< fa address-book >}} &nbsp;Supervision

#### Medical Students <br>

##### **EXSEL** (University of Leeds)
Olivia Carson (MBChB Y3) <br>
2023 - present | Multiple long-term conditions in patients admitted to hospital with heart failure.<br>

##### **ESREP** (University of Leeds)
Elizabeth Lee & Szymon Berus (MBChB Y4) <br>
2023 - present | Evaluating the representativeness of patients included in landmark trials for myocardial infarction.<br><br>
Wiktoria Ożarek & Eepsha Hiraluge (MBChB Y4) <br>
2023 - present | Neuropsyciatric multimorbidity in patients with acute myocardial infarction.<br>


### {{< fa people-line >}} &nbsp;Outreach and Engagement

**Nuffield Research Placement** <br>
The [Nuffield Research Placement](https://www.nuffieldresearchplacements.org/) scheme aims to provide engaging, hands-on research projects to Year 12 students from groups that are under-represented in STEM courses in higher education. I successfully hosted two students for a 2-week NRP in August 2023, teaching them some basic epidemiology and R skills.

**Principal Investigator, Data Study Group, Turing Institute** <br>
[Data Study Groups](https://www.turing.ac.uk/collaborate-turing/data-study-groups) are intensive 'collaborative hackathons', where researchers brainstorm and engineer data science solutions, presenting their work after the end of a week. I was invited to act as Prinicipal Investigator for a DSG, held in March 2023 at The Helix, Newcastle University, Newcastle Upon Tyne. This was entitled, "Exploring multimorbidity and patterns of long-term conditions in England using open
prescription and primary care data" and the full report is currently in press.

## {{< fa star >}} &nbsp;Other Indicators of Esteem
**Peer review** <br>
I peer review for a number of journals. Recently, these have included (in alphabetical order):
*BMJ*, *BMJ Public Health*, *Cardiology*, *Clinical Medicine*, *Diabetes and Vascular Disease Research*, *EHJ Case Reports*, *Heart*, *International Journal of Cardiology*, *Lancet*, *MedComm*, and *Systematic Reviews*.

**The UK Research and Innovation Talent Peer Review College**<br>
I am a member of the [UKRI Talent Peer Review College](https://www.ukri.org/publications/ukri-talent-peer-review-college-member-list/) and have provided expert, independent, informed reviews of research proposals submitted to UKRI bodies (e.g. MRC, EPSRC) for consideration for funding.

:::

::: {.g-col-4}
### {{< fa address-card >}} &nbsp;Key Details
{{< fa envelope >}} &nbsp;J.Batty@leeds.ac.uk <br>
{{< fa brands twitter >}} &nbsp;@JonnyBatty <br>
{{< fa user-doctor >}} &nbsp;&nbsp;GMC 7454712 <br>
For more information, please contact me via email.

### {{< fa wrench >}} &nbsp;Skills
**Research:** Data science and statistical analysis (Python, R, Stata), general programming (C++, JS, Bash), web development (HTML, JS, CSS), Git/GitHub.<br>
**Medical:** Clinical cardiology, coronary intervention, prevention of cardiovascular disease, general internal medicine.

### {{< fa bookmark >}} &nbsp;Interests
**Research:** cardiovascular disease, multiple long-term conditions, routinely-collected healthcare data, statistics, machine learning, data science. <br>
**Non-research:** reading (spy fiction/sci-fi), music (indie/rock), films, podcasts and sunny holidays!.
:::

:::


